### ISSUE TITLE
Lighthouse running against the live theme instead of the generated development/preview theme

### ISSUE THREAD

**Issue by darrylb-github** [Shopify/lighthouse-ci-action#18]
Hey,

Not sure if I'm missing something, but when trying to use this it seems to generate a preview theme successfully, but then not run lighthouse against it, instead running lighthouse against the live store from what I can tell.

My workflow:

```
name: Lighthouse
on: [push]
jobs:
  lighthouse:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lighthouse
        uses: shopify/lighthouse-ci-action@1.0
        with:
          store: '***.myshopify.com'
          
          app_id: ${{ secrets.SHOP_APP_ID }}
          app_password: ${{ secrets.SHOP_APP_PASSWORD }}
          lhci_github_token: ${{ secrets.LHCI_GITHUB_TOKEN }}

```

Logs with store name redacted:

```
Creating development theme
{"theme":{"id":125912940720,"name":"Development (12a77e-3d8c52211dfc)","role":"development","shop":"***.myshopify.com","editor_url":"https://***.myshopify.com/admin/themes/125912940720/editor","preview_url":"https://***.myshopify.com/?preview_theme_id=125912940720"}}
==============================
Configuring Lighthouse CI
==============================
Running Lighthouse CI
✅  .lighthouseci/ directory writable
✅  Configuration file found
✅  Chrome installation found
⚠️   GitHub token not set
Healthcheck passed!

Getting a new page...
Getting preview cookie...
Running Lighthouse 3 time(s) on https://***.myshopify.com/?_fd=0&pb=0
```

If I load the preview_url I get the expected development theme based on my current branch, but the lighthouse run for my branch runs against the normal store URL without the `preview_theme_id` set, and when loading up the report screenshots at the end of lighthouse I can see it's my live theme and not the development theme I'd expect for the branch lighthouse is being run against and generating a preview URL for.

Am I doing something wrong?

Thanks,
Darryl
