### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by brightonmike** [Shopify/lighthouse-ci-action#23]
I've set the shop password secret, and I've checked it works via the browser, but I'm getting a 401.

```
Configuring shopify CLI
Will run Lighthouse CI on https://***
==============================
Creating development theme
✗ Please login again with shopify login
==============================
Configuring Lighthouse CI
Fetching product handle
There's been an error when querying the API

curl: (22) The requested URL returned error: 401
```

This is with an as yet unmodified Dawn theme. Any ideas?

**Comment by poropatnico** [comment]
I've tried your solution (added both test products and collections) and nothing still. Same message as yours. 

Here's my lighthouserc.js file content which is se to repo root: 
`module.exports = {
    ci: {
      upload: {
        target: 'temporary-public-storage',
      },
    },
  };`

As well as my ci.yml snippet:

`name: Shopify Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Lighthouse
        uses: shopify/lighthouse-ci-action@1.0
        with:
          app_id: ${{ secrets.SHOP_APP_ID }}
          app_password: ${{ secrets.SHOP_APP_PASSWORD }}
          store: ${{ secrets.SHOP_STORE }}
          password: ${{ secrets.SHOP_PASSWORD }}
          lhci_github_app_token: ${{ secrets.LHCI_GITHUB_TOKEN }}
  theme-check:
    name: Theme Check
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Theme Check
        uses: shopify/theme-check-action@v1
        with:
          token: ${{ github.token }}`


Any ideas what I'm doing wrong?

**Comment by charlespwd** [comment]
Ugh. The docs haven't made it to shopify.dev yet and we haven't updated the dawn repo. 

If you look at the README you should see that authentication is done with Custom Apps now. Assuming you are working on a fork of Dawn, try the [new authentication method](https://github.com/Shopify/lighthouse-ci-action#authentication).

It should be this:

```yaml
name: Shopify Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Lighthouse
        uses: shopify/lighthouse-ci-action@1.0
        with:
          access_token: ${{ secrets.SHOP_ACCESS_TOKEN }}
          store: ${{ secrets.SHOP_STORE }}
          password: ${{ secrets.SHOP_PASSWORD }}
          lhci_github_app_token: ${{ secrets.LHCI_GITHUB_TOKEN }}
  theme-check:
    name: Theme Check
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Theme Check
        uses: shopify/theme-check-action@v1
        with:
          token: ${{ github.token }}
```
