### ISSUE TITLE
curl: (22) The requested URL returned error: 401 - Lighthouse CI action issue

### ISSUE THREAD

**Issue by poropatnico** [Shopify/lighthouse-ci-action#39]
I keep getting this error.

```
Configuring shopify CLI
Will run Lighthouse CI on https://***
==============================
Creating development theme
✗ Please login again with shopify login
==============================
Configuring Lighthouse CI
Fetching product handle
There's been an error when querying the API

curl: (22) The requested URL returned error: 401

```

I added test products, collections, all secrets, as well as the following: 

My lighthouserc.js file content which is se to repo root:

```
module.exports = {
    ci: {
      upload: {
        target: 'temporary-public-storage',
      },
    },
  };
```

As well as my ci.yml snippet:

```
name: Shopify Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Lighthouse
        uses: shopify/lighthouse-ci-action@1.0
        with:
          app_id: ${{ secrets.SHOP_APP_ID }}
          app_password: ${{ secrets.SHOP_APP_PASSWORD }}
          store: ${{ secrets.SHOP_STORE }}
          password: ${{ secrets.SHOP_PASSWORD }}
          lhci_github_app_token: ${{ secrets.LHCI_GITHUB_TOKEN }}
  theme-check:
    name: Theme Check
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Theme Check
        uses: shopify/theme-check-action@v1
        with:
          token: ${{ github.token }}

```
Any ideas what I'm doing wrong?
