### ISSUE TITLE
Error: Lighthouse failed with exit code 1 - DNS_FAILURE

### ISSUE THREAD

**Issue by 3daddict** [Shopify/lighthouse-ci-action#42]
I can't seem to find my way out of this error:
```
"lighthouseVersion": "8.0.0",
  "fetchTime": "2022-05-13T15:23:00.779Z",
  "requestedUrl": "https://***/?preview_theme_id=130421096632&_fd=0&pb=0",
  "finalUrl": "https://***/?preview_theme_id=130421096632&_fd=0&pb=0",
  "runWarnings": [
    "DNS servers could not resolve the provided domain."
  ],
  "runtimeError": {
    "code": "DNS_FAILURE",
    "message": "DNS servers could not resolve the provided domain."
  },
```
Here is my current action file
```yml
name: CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lighthouse
        uses: shopify/lighthouse-ci-action@1.0
        with:
          theme_root: ./dist
          store: ${{ secrets.SHOP_STORE }}
          access_token: ${{ secrets.SHOP_ACCESS_TOKEN }}
          product_handle: ${{ secrets.SHOP_PRODUCT_HANDLE }}
          collection_handle: ${{ secrets.SHOP_COLLECTION_HANDLE }}
          lhci_github_app_token: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          lhci_min_score_performance: 0.6
          lhci_min_score_accessibility: 0.9
```
I think I have everything passing as expected?
```
==============================
Configuring shopify CLI
Will run Lighthouse CI on https://***
==============================
Creating development theme
{"theme":{"id":130421293240,"name":"Development (b11ff0-f8e7f7bbfacc)","role":"development","shop":"***.myshopify.com","editor_url":"https://***.myshopify.com/admin/themes/130421293240/editor","preview_url":"https://***.myshopify.com/?preview_theme_id=130421293240"}}
==============================
Configuring Lighthouse CI
==============================
Running Lighthouse CI
✅  .lighthouseci/ directory writable
✅  Configuration file found
✅  Chrome installation found
✅  GitHub token set
Healthcheck passed!
Getting a new page...
Getting preview cookie...
Running Lighthouse 3 time(s) on https://***/?preview_theme_id=1304[21](https://github.com/***/***runs/6425936387?check_suite_focus=true#step:4:21)293[24](https://github.com/***/***/runs/6425936387?check_suite_focus=true#step:4:24)0&_fd=0&pb=0
```
