### ISSUE TITLE
SHOP_APP_PASSWORD: unbound variable

### ISSUE THREAD

**Issue by rahulpatidar0191** [Shopify/lighthouse-ci-action#65]
Similar to https://github.com/Shopify/lighthouse-ci-action/issues/45 but we are passing access_token

This workflow seems to work fine with no errors 
```yaml
    steps:
      - uses: actions/checkout@v3

      - name: Lighthouse CI
        uses: shopify/lighthouse-ci-action@v1
        with:
          store: ${{ secrets.STORE_NAME}}
          access_token: ${{ secrets.SHOP_ACCESS_TOKEN }}
          password: ${{ secrets.THEME_PASSWORD }}
          lhci_github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_theme: <theme_name>
```

But when we pass `product_handle` and `collection_handle`  we get  `SHOP_APP_PASSWORD: unbound variable` error
```YAML
      - name: Lighthouse CI
        uses: shopify/lighthouse-ci-action@v1
        with:
          store: ${{ secrets.STORE_NAME}}
          access_token: ${{ secrets.SHOP_ACCESS_TOKEN }}
          password: ${{ secrets.THEME_PASSWORD }}
          lhci_github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_theme: <theme_name>
          collection_handle: "<collection_handle>"
          product_handle: "<product_handle>"

```
